### ISSUE TITLE
Results tab not displaying subdirectories when multiple tests ran in sequence

### ISSUE THREAD

**Issue by rnp5285** [FuturePhotonInitiative/SPAE#23]
**Describe the bug**
After running a queue with multiple tests that produce individual folders of data, head to the results tab. The only data that shows up is the config json file. All data in subfolders are not accessible from the GUI.

**To Reproduce**
1. Run the program.
2. Select a at least two tests that produces data (IBERT, VAT, etc.) from the dropdown.
3. Select the "Add" button. 
4. Select the "Run Queue" button.
5. See the queue has completed successfully and no exceptions are raised on either terminal.
6. Select the "Results" tab.
7. Check the last queue run at the bottom to reproduce bug.

**Expected behavior**
There should be checks to see if there are folders at the end of execution to append subfolders to the Results tab. Data should be accessible in subfolders within the Results tab.

**Screenshots**
![bug](https://user-images.githubusercontent.com/35935051/70807811-47799a00-1d8c-11ea-9ecc-ba9417f642c0.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Computer (if named): blackdog

**Instruments Connected:** N/A

**Comment by abacef** [comment]
So yes, PTCS did not have the logic to display sub-directories as you said, but there was another issue:

So the deal was that a TCL experiment does not successfully add all the files it produces into the experiment result object, therefore since the the results tab just loads json result files and displays the files that each experiment generated, this list is never up to date.

Instead of trying to debug this, I am just going to walk the result directory myself every time a result is selected on the left panel.
